### PR TITLE
Overwrite special script tags 

### PR DESCRIPTION
**Pull request by hryvinskyi**
Added possibility overwrite special script tags on minify process

---
This change is [Reviewable](https://reviewable.io/reviews/voku/htmlmin/66)

### CODE REVIEW

**Comment by hryvinskyi** [comment]
@voku Can you chack this?

**Comment by voku** [comment]
@hryvinskyi Can you maybe add a simple test for this?

**Comment by voku** [comment]
@hryvinskyi Sorry for the delay... :-/ 

Thanks for the improvement, I will tag a new release now. :+1:

**Comment by hryvinskyi** [comment]
@voku thanks!

**Pull request merged**
